[package]
name = "dummyapi"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.116", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.2"
warp = "0.3"
